export const productsSeed = [
  {
    name: "Nebula Wireless Earbuds",
    description: "Spatial audio earbuds with active noise cancellation and a charging case that glows like a tiny galaxy.",
    price: 2499,
    category: "Audio",
    image: "https://picsum.photos/seed/nebula-earbuds/800/800",
    accentColor: "#8b5cf6",
    tag: "New",
  },
  {
    name: "Photon Mechanical Keyboard",
    description: "Hot-swappable switches, per-key RGB, and a machined aluminum frame built for late-night builds.",
    price: 4999,
    category: "Tech",
    image: "https://picsum.photos/seed/photon-keyboard/800/800",
    accentColor: "#06b6d4",
    tag: "Bestseller",
  },
  {
    name: "Aurora Ambient Lamp",
    description: "A softly shifting light sculpture that syncs its gradient to your music or your mood.",
    price: 1499,
    category: "Home",
    image: "https://picsum.photos/seed/aurora-lamp/800/800",
    accentColor: "#f472b6",
  },
  {
    name: "Vortex Gaming Mouse",
    description: "26,000 DPI sensor, zero-lag wireless, and a shell light enough to forget it's in your hand.",
    price: 2199,
    category: "Gaming",
    image: "https://picsum.photos/seed/vortex-mouse/800/800",
    accentColor: "#22c55e",
  },
  {
    name: "Pulse Fitness Band",
    description: "Tracks heart rate, sleep, and stress with a display bright enough for direct sunlight.",
    price: 1799,
    category: "Wearables",
    image: "https://picsum.photos/seed/pulse-band/800/800",
    accentColor: "#f59e0b",
  },
  {
    name: "Halo Desk Speaker",
    description: "A ring-shaped speaker that fills a room with 360-degree sound and a warm halo of light.",
    price: 3499,
    category: "Audio",
    image: "https://picsum.photos/seed/halo-speaker/800/800",
    accentColor: "#ef4444",
  },
  {
    name: "Drift Portable SSD",
    description: "2TB of storage that survives drops, dust, and deadlines. Transfers at blistering speed.",
    price: 6999,
    category: "Tech",
    image: "https://picsum.photos/seed/drift-ssd/800/800",
    accentColor: "#3b82f6",
    tag: "New",
  },
  {
    name: "Comet Smartwatch",
    description: "An always-on AMOLED display wrapped around a battery that actually lasts a week.",
    price: 5999,
    category: "Wearables",
    image: "https://picsum.photos/seed/comet-watch/800/800",
    accentColor: "#a855f7",
  },
  {
    name: "Ember Espresso Maker",
    description: "Precision temperature control for a perfect shot every time, wrapped in brushed steel.",
    price: 8999,
    category: "Home",
    image: "https://picsum.photos/seed/ember-espresso/800/800",
    accentColor: "#fb923c",
  },
  {
    name: "Zenith Gaming Headset",
    description: "Studio-tuned drivers and a mic that makes your squad forget you're not in the same room.",
    price: 3999,
    category: "Gaming",
    image: "https://picsum.photos/seed/zenith-headset/800/800",
    accentColor: "#14b8a6",
    tag: "Bestseller",
  },
  {
    name: "Flux Wireless Charger",
    description: "A levitating charging stand that spins your phone gently into place. Yes, really.",
    price: 1299,
    category: "Tech",
    image: "https://picsum.photos/seed/flux-charger/800/800",
    accentColor: "#e879f9",
  },
  {
    name: "Cascade Monitor Light",
    description: "Bias lighting that clips onto any monitor to cut eye strain during marathon sessions.",
    price: 999,
    category: "Home",
    image: "https://picsum.photos/seed/cascade-light/800/800",
    accentColor: "#38bdf8",
  },
  {
    name: "Nova Oversized Hoodie",
    description: "Heavyweight fleece with a dropped shoulder cut and a reflective print that catches the light.",
    price: 1899,
    category: "Clothing",
    image: "https://picsum.photos/seed/nova-hoodie/800/800",
    accentColor: "#f97316",
    tag: "New",
  },
  {
    name: "Drift Cargo Pants",
    description: "Technical cargo trousers with articulated knees and a tapered fit for everyday movement.",
    price: 2299,
    category: "Clothing",
    image: "https://picsum.photos/seed/drift-cargo/800/800",
    accentColor: "#65a30d",
  },
  {
    name: "Lumen Graphic Tee",
    description: "Soft-washed cotton with a glow-in-the-dark print that reveals itself after dark.",
    price: 799,
    category: "Clothing",
    image: "https://picsum.photos/seed/lumen-tee/800/800",
    accentColor: "#0ea5e9",
  },
  {
    name: "Solstice Bomber Jacket",
    description: "A water-resistant shell with a satin lining, built for city nights that get cold fast.",
    price: 3999,
    category: "Clothing",
    image: "https://picsum.photos/seed/solstice-jacket/800/800",
    accentColor: "#dc2626",
    tag: "Bestseller",
  },
  {
    name: "Orbit Chain Necklace",
    description: "A hand-finished stainless steel chain with a satellite pendant that catches every angle of light.",
    price: 2999,
    category: "Jewellery",
    image: "https://picsum.photos/seed/orbit-necklace/800/800",
    accentColor: "#eab308",
  },
  {
    name: "Glint Stud Earrings",
    description: "Minimal cubic zirconia studs set in hypoallergenic gold-plated steel — everyday shine.",
    price: 1499,
    category: "Jewellery",
    image: "https://picsum.photos/seed/glint-earrings/800/800",
    accentColor: "#facc15",
    tag: "New",
  },
  {
    name: "Meridian Cuff Bracelet",
    description: "An adjustable open cuff with a brushed matte finish that pairs with anything.",
    price: 2199,
    category: "Jewellery",
    image: "https://picsum.photos/seed/meridian-bracelet/800/800",
    accentColor: "#c084fc",
  },
  {
    name: "Astra Signet Ring",
    description: "A modern take on the classic signet, engraved with a constellation motif.",
    price: 1799,
    category: "Jewellery",
    image: "https://picsum.photos/seed/astra-ring/800/800",
    accentColor: "#fb7185",
  },
];
